Repository instructlab/eval, pull requests merged in 2024-10, with the labels that each got.

#143 Remove task logic with lm_eval 0.4.4 for agg_score
  src/instructlab/eval/mmlu.py
Labels: one-approval

#141 Add missing comment for error_rate return
  src/instructlab/eval/mt_bench.py
Labels: one-approval

#152 chore: rename 'basic-workflow-tests' to 'e2e-custom'
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD

#155 ci: change small E2E CI job to medium
  .github/mergify.yml
  .github/workflows/e2e-nvidia-a10g-x1.yml
  README.md
Labels: documentation, CI/CD, one-approval, ci-failure

#157 ci: add large-size E2E CI job
  .github/workflows/e2e-nvidia-l40s-x4.yml
  README.md
Labels: documentation, CI/CD, one-approval

#159 ci: use org variable for AWS EC2 AMI in E2E CI jobs
  .github/workflows/e2e-nvidia-a10g-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD

#162 ci: convert med E2E CI job to L4 GPU
  .github/mergify.yml
  .github/workflows/e2e-nvidia-l4-x1.yml
  README.md
Labels: documentation, CI/CD, one-approval

#163 feat: use custom http_client
  .spellcheck-en-custom.txt
  CHANGELOG.md
  requirements.txt
  src/instructlab/eval/mt_bench.py
  src/instructlab/eval/mt_bench_answers.py
  src/instructlab/eval/mt_bench_common.py
  src/instructlab/eval/mt_bench_judgment.py
  tests/test_branch_gen_answers.py
Labels: documentation, dependencies, CI/CD, testing, one-approval
