Repository instructlab/eval, pull requests merged in 2024-09, with the labels that each got.

#99 Allow for external serving to be used with mmlu
  requirements.txt
  src/instructlab/eval/mmlu.py
Labels: dependencies

#115 Cleanup usage of load model answers
  src/instructlab/eval/mt_bench_common.py
  src/instructlab/eval/mt_bench_judgment.py
Labels: one-approval

#128 add option to pass 'api_key' to gen_answers, judge_answers
  src/instructlab/eval/mt_bench.py
  src/instructlab/eval/mt_bench_answers.py
  src/instructlab/eval/mt_bench_common.py
  src/instructlab/eval/mt_bench_judgment.py
Labels: testing

#131 e2e: only run PR job if certain files are changed
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval

#107 Allow max_workers to be passed in after evaluator is created
  src/instructlab/eval/mt_bench.py
Labels: one-approval

#98 Remove fastchat dependency
  requirements.txt
  src/instructlab/eval/mt_bench_answers.py
  src/instructlab/eval/mt_bench_common.py
  src/instructlab/eval/mt_bench_conversation.py
  src/instructlab/eval/mt_bench_model_adapter.py
Labels: dependencies, CI/CD

#130 docs: update README with more contextual eval info
  .spellcheck-en-custom.txt
  README.md
Labels: documentation, CI/CD, one-approval

#136 github: add stale bot to eval repo
  .github/stale_bot.yml
Labels: one-approval

#137 ci: fix lint action
  .github/workflows/lint.yml
  .pylintrc
Labels: CI/CD, one-approval

#140 Remove max_workers and serving_gpus from constructor
  src/instructlab/eval/mt_bench.py
Labels: one-approval

#138 return overall_score from MTBenchBranch.generate_judgement()
  .github/workflows/e2e-nvidia-t4-x1.yml
  src/instructlab/eval/mt_bench.py
  tests/test_branch_judge_answers.py
Labels: CI/CD, testing, ci-failure
