Repository instructlab/eval, pull requests merged in 2024-08, with the labels that each got.

#118 ci: move E2E runner from github to AWS
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  .github/workflows/e2e.yml
Labels: CI/CD

#91 docs: add initial release strategy doc and CHANGELOG
  .spellcheck-en-custom.txt
  CHANGELOG.md
  docs/release-strategy.md
Labels: documentation, CI/CD, one-approval

#120 CI: Fix working directories to be relative
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, ci-failure
