Repository instructlab/eval, pull requests merged in 2025-01, with the labels that each got.

#210 chore: Change default temporary write directory in all e2e CI jobs from `tmpfs` to `/home/tmp`
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD

#212 Bump ragas version
  requirements.txt
  src/instructlab/eval/ragas.py
Labels: dependencies

#221 ci: Add OpenAI keys into CI
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval, ci-failure
