Repository instructlab/eval, pull requests merged in 2025-06, with the labels that each got.

#268 chore: Remove python 3.10 remnants
  docs/ci.md
  requirements-leaderboard.txt
Labels: dependencies

#276 chore: Uncap some requirements dependencies
  requirements.txt
Labels: dependencies, one-approval

#275 add DCO.txt and remove mergify DCO requirement
  .github/mergify.yml
  DCO.txt
  README.md
Labels: documentation, CI/CD

#281 chore: Add EC2 fallback logic CI-ACTION to medium + large E2E jobs
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval

#249 Add LongBench V2 benchmark
  pyproject.toml
  requirements-cuda.txt
  requirements-longbench.txt
  src/instructlab/eval/longbench.py
  tests/test_project.py
Labels: dependencies, testing

#283 chore: update constraints-dev.txt (2025-06-16)
  constraints-dev.txt
Labels: one-approval

#287 ci: Remove harden-runner steps from jobs
  .github/workflows/actionlint.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/pypi.yaml
  .github/workflows/test.yml
Labels: CI/CD, one-approval
